logging.file.name=logs/tech_cup.log

# Credentials for PostgreSQL database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA / Hibernate
# 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=create

# Muestra el SQL en la consola (Muy útil para ver qué tablas está creando)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT config
jwt.secret=${JWT_SECRET:my-super-secret-key-that-should-be-overridden-in-production-1234567890}
jwt.access-token-expiration-minutes=15
jwt.refresh-token-expiration-days=7