logging.file.name=logs/tech_cup.log

# Credentials for PostgreSQL database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA / Hibernate
# 'create' crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=create

# Muestra el SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Security (credenciales personalizadas)
spring.security.user.name=techcupadmin
spring.security.user.password=Tc2026Secure